config/routes.rb
Blog::Application.routes.draw do
  mount RailsAdmin::Engine => '/User', :as => 'rails_admin'

  devise_for :users

  resources :posts do
    resources :comments
  end
  

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title, :published
  validates :name, :presence => true
  validates :title, :presence => true,
		    :length => { :minimum => 5 }
  has_many :comments, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.create(params[:comment])
      redirect_to post_path(@post)
    end
#     def show
#     @comment = Comment.find(params[:id])
# 
#     respond_to do |format|
#       format.html # show.html.erb
#       format.json { render json: @comment }
#       end
#     end
     def destroy
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      redirect_to post_path(@post)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.page(params[:page]).per(2)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Entrada publicada correctamente.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Entrada actualizada correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p>
  <b>Autor: </b>
  <%= comment.commenter %>
</p>
<p>
  <b>Comentario: </b>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Borrar comentario', [comment.post, comment], 
		:method => :delete,
		:confirm => 'Seguro?' %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style = "background: #959595">

<div id="user_nav">
  <% if user_signed_in? %>
    Eres <%= current_user.email %>, No pollo?
    <%= link_to 'Salir', destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to 'Registrarse', new_user_registration_path %> o 
    <%= link_to 'Iniciar sesion', new_user_session_path %>
  <% end %>
</div>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
<!--  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %> -->

  <div class="field">
  <!--   <%= f.label "Nombre" %><br />
   <%= f.text_field :name %> -->
    <%= f.input :name, :label => 'Nombre'%>
  </div>
  <div class="field">
<!--    <%= f.label "Titulo" %><br />
    <%= f.text_field :title %> -->
    <%= f.input :title , :label => 'Titulo'%>
  </div>
  <div class="field">
 <!--   <%= f.label "Entrada" %><br />
    <%= f.text_area :content %> -->
    <%= f.input :content, as: :text, :label => 'Contenido:' %>
  </div>
  <div class="field">
<!--    <%= f.label "Publicado" %>
    <%= f.check_box :published %> -->
    <%= f.input :published, as: :boolean, :label => 'Publicado' %>
  </div>
  <div class="actions">
   <!-- <%= f.submit %>-->
   <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Lista de entradas</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Titulo</th>
    <th>Contenido</th>
    <th>Publicado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<%= paginate @posts %>
<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= post.published %></td>
    <td><%= link_to 'Ver', post %></td>
    <td><%= link_to 'Editar', edit_post_path(post) %></td>
    <td><%= link_to 'Borrar', post, method: :delete, data: { confirm: 'Seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva entrada', new_post_path %>

app/views/posts/new.html.erb
<h1>Nueva entrada</h1>

<%= render 'form' %>

<%= link_to 'volver', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @post.name %>
</p>

<p>
  <b>Titulo:</b>
  <%= @post.title %>
</p>

<p>
  <b>Contenido:</b>
  <%= @post.content %>
</p>

<h2>Comentarios</h2>
<%= render @post.comments %>


<h2>Añadir un comentario:</h2>
<%= simple_form_for ([@post, @post.comments.build]) do |f| %>
  <div class="field">
 <!--   <%= f.label :Autor %><br />
    <%= f.text_field :commenter %> -->
    <%= f.input :commenter, :label => 'Autor' %>
  </div>
  <div class="field">
 <!--   <%= f.label :Comentario %><br />
    <%= f.text_area :body %><br /> -->
    <%= f.input :body, as: :text, :label => 'Comentario' %>
  </div>
  <div class="actions">
  <!--  <%= f.submit %> -->
    <%= f.button :submit %>
  </div>
<% end %>


<%= link_to 'Editar', edit_post_path(@post) %> |
<%= link_to 'Volver', posts_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>